# Generated by Django 5.2.3 on 2025-06-23 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion'), ('other', 'Autre')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
            },
        ),
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('requested_quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('1440p', '1440p (2K)'), ('2160p', '2160p (4K)'), ('best', 'Meilleure qualité disponible'), ('worst', 'Qualité minimale')], default='best', max_length=20)),
                ('download_audio_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('actual_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.platform')),
            ],
            options={
                'verbose_name': 'Téléchargement de vidéo',
                'verbose_name_plural': 'Téléchargements de vidéos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_used', models.CharField(blank=True, max_length=100, null=True)),
                ('format_id', models.CharField(blank=True, max_length=50, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('fps', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('uploader', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='downloader.videodownload')),
            ],
            options={
                'verbose_name': 'Historique de téléchargement',
                'verbose_name_plural': 'Historiques de téléchargement',
            },
        ),
        migrations.CreateModel(
            name='DownloadStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('successful_downloads', models.PositiveIntegerField(default=0)),
                ('failed_downloads', models.PositiveIntegerField(default=0)),
                ('total_size_mb', models.PositiveBigIntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.platform')),
            ],
            options={
                'verbose_name': 'Statistique de téléchargement',
                'verbose_name_plural': 'Statistiques de téléchargement',
                'ordering': ['-date'],
                'unique_together': {('platform', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SupportedFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('is_video', models.BooleanField(default=True)),
                ('is_audio', models.BooleanField(default=False)),
                ('max_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.platform')),
            ],
            options={
                'verbose_name': 'Format supporté',
                'verbose_name_plural': 'Formats supportés',
                'unique_together': {('platform', 'format_name')},
            },
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['status', 'created_at'], name='downloader__status_2e59fe_idx'),
        ),
        migrations.AddIndex(
            model_name='videodownload',
            index=models.Index(fields=['platform', 'created_at'], name='downloader__platfor_d1ba5b_idx'),
        ),
    ]
