# Generated by Django 5.2.3 on 2025-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownload',
            name='requested_quality',
            field=models.CharField(default='best', max_length=50),
        ),
    ]
